
    console.log(customer);
  } catch (err) {
    console.log(err);